### PR TITLE
tmux: update config

### PR DESCRIPTION
**Pull request by TomaszAIR**

### CODE REVIEW

**Review by PLangowski — COMMENTED** [review]
This works. However, there is an issue in line 13:
`bind-key -t copy-mode-vi-copy 'v' send-keys -X begin-selection`.
I results in the following erroe: `tmux.conf:13: command bind-key: unknown flag -t`.
This is probably a typo. Changing the option to capital -T fixes it. Maybe we should fix it in this PR as well? @TomaszAIR

**Comment by TomaszAIR** [comment]
@PLangowski we should, could you please push needed change to this branch?

**Comment by PLangowski** [comment]
> @PLangowski we should, could you please push needed change to this branch?

done 111a587e0bb44a2747616db0e869762ab55a64e8

**Comment by PLangowski** [comment]
@TomaszAIR Is it okay for me to approve a PR when I was the last one to push a commit to it?

**Comment by TomaszAIR** [comment]
> @TomaszAIR Is it okay for me to approve a PR when I was the last one to push a commit to it?

It is

**Review by PLangowski — APPROVED** [review]
I think we're good to merge.

**Pull request merged**
